### 01. Importing Dependecies

In [1]:
import numpy as np
import pandas as pd

### 02. Import Dataset

In [2]:
df = pd.read_csv("data/processed/estate_missing_values_handled.csv")
df.head()

,IncomeLevel,PropertyAge,TotalRooms,TotalBedrooms,NeighborhoodPop,AvgOccupancy,Latitude,Longitude,TargetPrice,RoomsPerHousehold,BedroomsRatio
0,3.287977,32.970198,5.128150,0.990769,2339.474039,3.739113,32.71,-117.03,1.030,1.359130,0.200576
1,3.804601,49.030192,4.372696,1.040469,1269.383596,1.429576,33.77,-118.16,3.821,2.573820,0.232703
2,2.029509,36.255617,4.131418,1.032285,1455.381923,3.914447,32.69,-117.11,0.934,1.002116,0.258269
3,3.540823,42.918534,6.270531,1.147146,895.050628,2.681969,36.78,-119.80,0.965,2.725400,0.180940
4,6.609324,20.212848,6.178103,0.986182,2698.088189,3.457448,37.42,-121.86,2.648,1.867161,0.160572

### 03. Feature Binning

In [3]:
def property_age_binning(age):
    if age <= 15:
        return 'New'
    elif age <= 35:
        return 'Moderate'
    else:
        return 'Old'

In [4]:
df['PropertyAge_bins'] = df['PropertyAge'].apply(property_age_binning)
del df['PropertyAge']

In [5]:
df.head()

,IncomeLevel,TotalRooms,TotalBedrooms,NeighborhoodPop,AvgOccupancy,Latitude,Longitude,TargetPrice,RoomsPerHousehold,BedroomsRatio,PropertyAge_bins
0,3.287977,5.128150,0.990769,2339.474039,3.739113,32.71,-117.03,1.030,1.359130,0.200576,Moderate
1,3.804601,4.372696,1.040469,1269.383596,1.429576,33.77,-118.16,3.821,2.573820,0.232703,Old
2,2.029509,4.131418,1.032285,1455.381923,3.914447,32.69,-117.11,0.934,1.002116,0.258269,Old
3,3.540823,6.270531,1.147146,895.050628,2.681969,36.78,-119.80,0.965,2.725400,0.180940,Old
4,6.609324,6.178103,0.986182,2698.088189,3.457448,37.42,-121.86,2.648,1.867161,0.160572,Moderate

In [6]:
df.to_csv("data/processed/estate_Binning_Applied.csv",index=False)